### ISSUE TITLE
格式化后的代码不符合 PSR-2 规范

### ISSUE THREAD

**Issue by VarroReve** [zgh-yuanshang/PhpStorm-Plugins#1]
按照 PSR-2 规范：
```
2.2 文件

......
所有 PHP 文件 必须 以一个空白行作为结束。
......
```

在使用 ALT + F 格式化导入类后，文件最后的一行空白行会被删除，希望可以保留空白行。OwO

**Comment by falling-ts** [comment]
> 按照 PSR-2 规范：
> 
> ```
> 2.2 文件
> 
> ......
> 所有 PHP 文件 必须 以一个空白行作为结束。
> ......
> ```
> 
> 在使用 ALT + F 格式化导入类后，文件最后的一行空白行会被删除，希望可以保留空白行。OwO

感谢提醒，马上修改更新
